GOOSE_MODEL: claude-sonnet-4.5
GOOSE_PROVIDER: github_copilot
extensions:
  developer:
    available_tools: []
    bundled: true
    description: Code editing and shell access
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
