GOOSE_MODEL: claude-sonnet-4.5
GOOSE_PLANNER_MODEL: gpt-5-codex
# x-advanced-models:
# - model: gpt-5
#   provider: github_copilot
#   role: deep-thinker
# - model: claude-sonnet-4.5
#   provider: github_copilot
#   role: coder
# - model: claude-haiku-4.5
#   provider: github_copilot
#   role: debugger
GOOSE_CLI_THEME: dark
GOOSE_MODE: auto
GOOSE_ENABLE_ROUTER: 'false'
GOOSE_PROVIDER: github_copilot
extensions:
  autovisualiser:
    available_tools: []
    bundled: true
    description: Data visualisation and UI generation tools
    display_name: Auto Visualiser
    enabled: false
    name: autovisualiser
    timeout: 300
    type: builtin
  brave-search:
    args:
    - -y
    - '@modelcontextprotocol/server-brave-search'
    available_tools: []
    bundled: null
    cmd: npx
    description: Search the web
    enabled: true
    env_keys:
    - BRAVE_API_KEY
    envs: {}
    name: brave-search
    timeout: 300
    type: stdio
  context7:
    args:
    - -y
    - '@upstash/context7-mcp'
    available_tools: []
    bundled: null
    cmd: npx
    description: Getting up-to-date, version-specific code and documentation. Use frequently
    enabled: true
    env_keys: []
    envs: {}
    name: context7
    timeout: 300
    type: stdio
  developer:
    available_tools: []
    bundled: true
    description: Code editing and shell access
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  extensionmanager:
    available_tools: []
    bundled: true
    description: Enable extension management tools for discovering, enabling, and disabling extensions
    enabled: true
    name: Extension Manager
    type: platform
  memory:
    available_tools: []
    bundled: true
    description: Tools to save and retrieve durable memories
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
  pdf:
    args:
    - mcp-read-pdf
    available_tools: []
    bundled: null
    cmd: uvx
    description: Read and extract text from PDFs
    enabled: true
    env_keys: []
    envs: {}
    name: pdf
    timeout: 300
    type: stdio
  todo:
    available_tools: []
    bundled: true
    description: Enable a todo list for Goose so it can keep track of what it is doing
    enabled: true
    name: todo
    type: platform
