model = "gpt-5-codex"
model_reasoning_effort = "medium"

[mcp_servers.mcphub]
command = "npx"
args = [
  "-y",
  "mcp-remote",
  "http://localhost:40075/mcp",
]

[projects."/Users/ezracerpac/Projects/Courses/PrepCourseSciCo"]
trust_level = "trusted"

[projects."/Users/ezracerpac/.local/share/chezmoi"]
trust_level = "trusted"

[projects."/Users/ezracerpac/Projects/Courses/ScientificComputing/Exercises/ex01-529793-cerpac-ezra"]
trust_level = "trusted"

[projects."/Users/ezracerpac/Projects/Courses/ScientificComputing"]
trust_level = "trusted"
