[tools]
node = "lts"
neovim = "latest"
starship = "latest"
fzf = "latest"
ripgrep = "latest"
fd = "latest"
bat = "latest"
eza = "latest"
zoxide = "latest"
delta = "latest"
jq = "latest"
atuin = "latest"
gum = "latest"
yazi = "latest"
carapace = "latest"
gh = "latest"
jjui = "latest"
tmux = "latest"
uv = "latest"
usage = "latest"
